#include "app/helpers.h"
#include <TFT_eSPI.h>
#include <stdint.h>

#ifndef COLOURS_H
#define COLOURS_H

#define FOUR_BIT_BLACK 0
#define FOUR_BIT_DARK_BLUE 1
#define FOUR_BIT_BLUE 2
#define FOUR_BIT_LIGHT_BLUE 3
#define FOUR_BIT_CYAN 4
#define FOUR_BIT_GREEN 5
#define FOUR_BIT_RED 6
#define FOUR_BIT_DARK_PURPLE 7
#define FOUR_BIT_DARK_GREY 8
#define FOUR_BIT_WHITE 9
#define FOUR_BIT_YELLOW 10
#define FOUR_BIT_VIOLET 11
#define FOUR_BIT_NAVY 12
#define FOUR_BIT_DARK_GREEN 13
#define FOUR_BIT_MAROON 14
#define FOUR_BIT_GREY 15

#define TFT_BACKGROUND TFT_BLACK
#define TEMPERATURE_COLOUR TFT_RED
#define WIND_COLOUR TFT_YELLOW
#define RAIN_COLOUR TFT_SKYBLUE
#define HUMIDITY_COLOUR 0x06E0
#define HUMIDITY_PCT_COLOUR_ACTIVE HUMIDITY_COLOUR
#define HUMIDITY_PCT_COLOUR_INACTIVE TFT_DARKGREEN
#define SUN_RISE_COLOUR 0xFD10
#define SUN_SET_COLOUR 0xFA60
#define MOON_OUTLINE_DARK 0x39a7

const uint16_t text_palette[] PROGMEM = {
    TFT_BACKGROUND,
    TFT_WHITE,
};

#define COLOURS_TEXT_BACKGROUND 0
#define COLOURS_TEXT_FOREGROUND 1

#define COLOURS_GRAPH_BACKGROUND FOUR_BIT_BLACK
#define COLOURS_GRAPH_FOREGROUND FOUR_BIT_WHITE
#define COLOURS_GRAPH_FADED FOUR_BIT_DARK_GREY

#define COLOURS_SOLAR_CYCLE_NIGHT_CIV FOUR_BIT_VIOLET
#define COLOURS_SOLAR_CYCLE_NIGHT_NAUT FOUR_BIT_DARK_GREY
#define COLOURS_SOLAR_CYCLE_DAY FOUR_BIT_CYAN
#define COLOURS_SOLAR_CYCLE_NOW_DAY FOUR_BIT_YELLOW
#define COLOURS_SOLAR_CYCLE_NOW_NIGHT FOUR_BIT_GREY

#define COLOURS_MOON_FACE FOUR_BIT_WHITE
#define COLOURS_MOON_BACKGROUND FOUR_BIT_BLACK
#define COLOURS_MOON_TERMINATOR_THIN FOUR_BIT_VIOLET
#define COLOURS_MOON_TERMINATOR_THICK FOUR_BIT_DARK_PURPLE

#endif