#ifndef LAYOUT_H
#define LAYOUT_H

/**********************************************************
* Borders
**********************************************************/
#define BORDERS_TOP_Y 28

/**********************************************************
* Time
**********************************************************/
#define TIME_SPRITE_WIDTH 64
#define TIME_SPRITE_HEIGHT 22
#define TIME_SPRITE_X 0
#define TIME_SPRITE_Y 0

#define MOON_SPRITE_WIDTH 20
#define MOON_SPRITE_HEIGHT 20
#define MOON_SPRITE_X TIME_SPRITE_WIDTH
#define MOON_SPRITE_Y 2

/**********************************************************
* Wifi
**********************************************************/
#define WIFI_MSG_SPRITE_WIDTH 230
#define WIFI_MSG_SPRITE_HEIGHT 26
#define WIFI_MSG_SPRITE_X TIME_SPRITE_WIDTH
#define WIFI_MSG_SPRITE_Y 0

#define WIFI_STATUS_SPRITE_WIDTH 24
#define WIFI_STATUS_SPRITE_HEIGHT 16
#define WIFI_STATUS_SPRITE_X (320 - WIFI_STATUS_SPRITE_WIDTH)
#define WIFI_STATUS_SPRITE_Y 4

/**********************************************************
* Data
**********************************************************/
#define DATA_STATUS_SPRITE_WIDTH 24
#define DATA_STATUS_SPRITE_HEIGHT 16
#define DATA_STATUS_SPRITE_X (320 - (WIFI_STATUS_SPRITE_WIDTH + DATA_STATUS_SPRITE_WIDTH))
#define DATA_STATUS_SPRITE_Y 5

#define DATA_PANEL_TOP BORDERS_TOP_Y
#define DATA_WIDGET_LINE_X 280

#define TEMPERATURE_TEXT_SPRITE_WIDTH 170
#define TEMPERATURE_TEXT_SPRITE_HEIGHT 70
#define TEMPERATURE_TEXT_SPRITE_X (320 - TEMPERATURE_TEXT_SPRITE_WIDTH)
#define TEMPERATURE_TEXT_SPRITE_Y (DATA_PANEL_TOP + 4)

#define TEMPERATURE_GRAPH_SPRITE_X 0
#define TEMPERATURE_GRAPH_SPIRTE_Y (DATA_PANEL_TOP + 8)
#define TEMPERATURE_GRAPH_HEIGHT 122
#define TEMPERATURE_GRAPH_WIDTH (140)

#define UV_SPRITE_HEIGHT 33
#define UV_SPRITE_WIDTH 41
#define UV_SPRITE_X (320 - UV_SPRITE_WIDTH - 8)
#define UV_SPRITE_Y (DATA_PANEL_TOP + 80)
#define UV_SPRITE_TRIANGLE_POINTS 0, 32, 20, 0, 40, 32
#define UV_SPRITE_TEXT_X 20
#define UV_SPRITE_TEXT_Y 19

#define RISE_SET_SPRITE_WIDTH 160
#define RISE_SET_SPRITE_HEIGHT 18
#define RISE_SET_SPRITE_X (320 - RISE_SET_SPRITE_WIDTH - 2)
#define RISE_SET_SPRITE_Y (UV_SPRITE_Y + UV_SPRITE_HEIGHT + 8)
#define RISE_SET_TRIANGLE_UP(x) x, 12, x - 4, 4, x - 8, 12
#define RISE_SET_TRIANGLE_DOWN(x) x, 4, x - 4, 12, x - 8, 4

#define WIND_LABEL_Y 175
#define WIND_TEXT_SPRITE_WIDTH 170
#define WIND_TEXT_SPRITE_HEIGHT 40
#define WIND_TEXT_SPRITE_X (320 - WIND_TEXT_SPRITE_WIDTH)
#define WIND_TEXT_SPRITE_Y (WIND_LABEL_Y + 20)

#define WIND_GRAPH_SPRITE_X 0
#define WIND_GRAPH_SPIRTE_Y WIND_LABEL_Y + 24
#define WIND_GRAPH_HEIGHT (RAIN_LABEL_Y - WIND_LABEL_Y - 40)
#define WIND_GRAPH_WIDTH (170)

#define COMPASS_RADIUS 24
#define ARROW_SPRITE_WIDTH 9
#define ARROW_SPRITE_HEIGHT (COMPASS_RADIUS * 2)
#define ARROW_SPRITE_X (320 - ((320 - WIND_GRAPH_WIDTH) / 2)) + 5
#define ARROW_SPRITE_Y (WIND_TEXT_SPRITE_Y + 76)

#define RAIN_LABEL_Y 320
#define RATE_TEXT_SPRITE_WIDTH 150
#define RATE_TEXT_SPRITE_HEIGHT 40
#define RATE_TEXT_SPRITE_X (320 - RATE_TEXT_SPRITE_WIDTH)
#define RATE_TEXT_SPRITE_Y (RAIN_LABEL_Y + 20)

#define CURRENT_TEXT_SPRITE_WIDTH 140
#define CURRENT_TEXT_SPRITE_HEIGHT 40
#define CURRENT_TEXT_SPRITE_X (320 - CURRENT_TEXT_SPRITE_WIDTH)
#define CURRENT_TEXT_SPRITE_Y RATE_TEXT_SPRITE_Y + 64

#define RAIN_GRAPH_SPRITE_X 0
#define RAIN_GRAPH_SPIRTE_Y RAIN_LABEL_Y + 24
#define RAIN_GRAPH_HEIGHT (HUMIDITY_LABEL_Y - RAIN_LABEL_Y - 40)
#define RAIN_GRAPH_WIDTH (190)

#define HUMIDITY_LABEL_Y 460
#define HUMIDITY_TEXT_SPRITE_WIDTH 70
#define HUMIDITY_TEXT_SPRITE_HEIGHT 30
#define HUMIDITY_TEXT_SPRITE_X (320 - HUMIDITY_TEXT_SPRITE_WIDTH)
#define HUMIDITY_TEXT_SPRITE_Y (HUMIDITY_LABEL_Y)
#define HUMIDITY_PCT_SPRITE_X 92
#define HUMIDITY_PCT_SPRITE_Y (HUMIDITY_LABEL_Y + 4)
#define HUMIDITY_PCT_SPRITE_WIDTH (320 - HUMIDITY_TEXT_SPRITE_WIDTH - HUMIDITY_PCT_SPRITE_X)
#define HUMIDITY_PCT_SPRITE_HEIGHT (11)

#define SOLAR_CYCLE_SPRITE_WIDTH 100
#define SOLAR_CYCLE_SPRITE_HEIGHT UV_SPRITE_HEIGHT - 2
#define SOLAR_CYCLE_SPRITE_X (UV_SPRITE_X - SOLAR_CYCLE_SPRITE_WIDTH - 16)
#define SOLAR_CYCLE_SPRITE_Y (RISE_SET_SPRITE_Y - SOLAR_CYCLE_SPRITE_HEIGHT - 6)

#endif