#ifndef TASKS_H
#define TASKS_H

#define KB(n) (1024 * n)

#define TASK_TOOLBAR_RENDER_STACK KB(3)
#define TASK_TOOLBAR_RENDER_PRIORITY 4

#define WIFI_MANAGER_STACK KB(4)
#define WIFI_MANAGER_PRIORITY 1

#define CLOCK_MANAGER_STACK KB(3)
#define CLOCK_MANAGER_PRIORITY 1

#define DATA_MANAGER_STACK KB(4)
#define DATA_MANAGER_PRIORITY 1

#define TEMPERATURE_WIDGET_STACK KB(3)
#define TEMPERATURE_WIDGET_PRIORITY 3

#define RAIN_WIDGET_STACK KB(3)
#define RAIN_WIDGET_PRIORITY 3

#define SUN_WIDGET_STACK KB(2)
#define SUN_WIDGET_PRIORITY 3

#define ATMOSPHERE_WIDGET_STACK KB(2)
#define ATMOSPHERE_WIDGET_PRIORITY 3

#define WIND_WIDGET_STACK KB(3)
#define WIND_WIDGET_PRIORITY 3

#define SCREEN_SERVER_STACK KB(2)
#define SCREEN_SERVER_PRIORITY 1

#endif