#ifndef CONFIG_H
#define CONFIG_H

#define APP_CORE 1 /* App on Core-1 as WiFi on Core-2 */
#define ENABLE_STATUS_MSG 0
#define CATEGORY_FONT_SIZE 3
#define TITLE_FONT_SIZE 2
#define DATA_UPDATE_PERIOD 5000
#define GRAPH_UPDATE_PERIOD 30000
#define GRAPH_UPDATE_INTERVAL (GRAPH_UPDATE_PERIOD / DATA_UPDATE_PERIOD)
#define LATITUDE 41.12345
#define LONGITUDE -87.98765
#define DST_OFFSET -5
#define WIND_DIRECTION_NORTH_OFFSET -90

#endif